### ISSUE TITLE
[bug] There will be a % character after startup

### ISSUE THREAD

**Issue by d1y** [vercel/hyper#3939] opened 2019-11-01 04:25 UTC
I have a % character after startup, it’s really uncomfortable.

![image](https://user-images.githubusercontent.com/45585937/68002211-b26e8600-fca2-11e9-9b98-a66d74bd5a50.png)

**Comment by d1y** [comment] 2019-11-01 04:26
![image](https://user-images.githubusercontent.com/45585937/68002236-cf0abe00-fca2-11e9-8099-a7d6da7e70b9.png)

**Comment by bet4it** [comment] 2019-11-01 05:02
Duplicate of #3586

**Comment by d1y** [comment] 2019-11-01 05:29
solved. editor `.zshrc` append

```bash
unsetopt PROMPT_SP
```

**Closed** 2020-06-26 15:49 UTC
