### ISSUE TITLE
Cannot be opened on MacOS

### ISSUE THREAD

**Issue by brightonmike** [vercel/hyper#5965] opened 2021-09-21 14:19 UTC
OS blocks opening:
"“Hyper” can’t be opened because Apple cannot check it for malicious software.“Hyper” can’t be opened because Apple cannot check it for malicious software."
MacBook Pro (13-inch, M1, 2020)
Chip Apple M1

**Comment by LabhanshAgrawal** [comment] 2021-09-21 16:37
Duplicate of #5779

**Closed by LabhanshAgrawal** 2021-09-21 16:37 UTC
