### ISSUE TITLE
Configurable double click selection separator characters

### ISSUE THREAD

**Issue by reflog** [vercel/hyper#501] opened 2016-07-29 12:58 UTC
Hi.
Is there any way to configure double click selection separator characters?

Right now, if I double click 'this-is-a-text' only the word 'this' is selected.

In most terminal applications, you can configure a set of characters, like '-_=' , etc to be included so that the whole word is selected. Very useful while coding :)

Thanks in advance!

**Comment by CodeTheory** [comment] 2016-07-29 12:59
Duplicate of #227.

**Comment by masylum** [comment] 2016-12-19 12:48
This is actually not closed. There is no way of configuring double click separator characters like in other terms. I think it would be great to reopen it.

Example in iterm:

![](https://www.dropbox.com/s/9wmc4t731amaoys/Screenshot%202016-12-19%2013.47.29.png?dl=1)

**Comment by CodeTheory** [comment] 2016-12-19 12:50
@masylum Perhaps your comments should go in the aforementioned issue that this is a duplicate of?

**Comment by masylum** [comment] 2016-12-20 09:10
Well, my point is that this is not a duplicated issue. The issue https://github.com/zeit/hyper/issues/227 just asks for hyphens to be included (a specific use case that was actually solved) this one asks for configurability (solves any use case). Otherwise every now and then we will receive issues about certain characters being or not included.

I can try to work on it if we reopen it. Shouldn't be difficult (famous last words)

**Comment by CodeTheory** [comment] 2016-12-20 13:44
Makes sense @masylum. I was kind of thinking that it was along the same lines so it could extend the issue I linked.

I'll re-open this. If you could give it a shot, that'd be great!

**Comment by dsully** [comment] 2018-06-21 17:30
+1 would love to see this.

**Comment by RichardBronosky** [comment] 2018-09-14 19:37
What ever came of this?

**Comment by mbhall88** [comment] 2019-06-27 13:03
Just wanting to bring this back to life again. This feature would be a huge time-saver.

**Comment by ericslaw** [comment] 2020-06-26 15:38
I'd like to see ':' _excluded_ from being considered a 'word' on macOS.
They used to have an 'language' definition for 'ascii' years ago but have since removed.
For some unexplained reason, ':' is now somehow considered a word? 🤯

**Comment by oshaughnessy** [comment] 2021-02-03 15:48
+1

**Closed** 2022-04-22 09:01 UTC
Labels: 🎨 Type: Enhancement, 👆 Is Upstream
