### ISSUE TITLE
Tab do not respond & squash/stretching on resize

### ISSUE THREAD

**Issue by nicobarray** [vercel/hyper#3593] opened 2019-05-06 10:06 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Mojave 10.14.4
- **Hyper.app version**: 3.0.0 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/nicobarray/fecc814d0dddd509e2c79e8d8e8aeb58
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
![image](https://user-images.githubusercontent.com/3589541/57218336-57125280-6ff5-11e9-8084-66904a068ba2.png)

- **The issue is reproducible in vanilla Hyper.app**: Unfortunately I couldn't.

## Issue

After updating to hyper v3.0.0 I had a weird behavior when creating a new vertical pane (with Cmd+Shift+D shortcut). The previous pane (the top one) stopped updating and it was totally stretch and squashed when resizing the pane (when the new pane poped and manually too afterward).

Notes:
The scrolling on the pane is not working too.
Other pane on the same tab are working.
The previous pane was running some lerna/dev servers.

Here is a small kap of the describe behavior:
![hyper3 0 0-stretching](https://user-images.githubusercontent.com/3589541/57218632-123aeb80-6ff6-11e9-9648-8960acf3486a.gif)

**Comment by ppot** [comment] 2019-05-10 21:26
@juancampa  need to update xtermjs version since it was fixed in a release

**Comment by nicobarray** [comment] 2019-05-11 11:23
I had this issue again (even if @ppot says it is fixed I want to add more context until the issue is closed). It appears to only impact the top left pane (feels like it is the first node of the pane tree).

Here are some more devtools screens (showing another error type: `Uncaught TypeError: Cannot read property 'replaceCells' of undefined`)

![image](https://user-images.githubusercontent.com/3589541/57569031-ea7dc600-73ef-11e9-8607-1f9ecba95daa.png)

**Comment by ppot** [comment] 2019-05-12 20:42
@nicobarray I said it was fixed in xterm, not in hyper since it pull on older xterm release.

**Comment by nicobarray** [comment] 2019-07-30 06:00
Hi @ppot, just wanted to know if hyper will update its xterm version in a next patch or canary release ?

**Comment by LabhanshAgrawal** [comment] 2020-07-05 12:45
We're on the latest xterm
can you try the latest [ci build](https://github.com/vercel/hyper/actions/runs/157826845) and confirm if it's fixed.

**Comment by nicobarray** [comment] 2020-07-07 14:48
I'll install the ci build and tell you if something fails (or not 🎉 ). Thanks for the work!

**Comment by LabhanshAgrawal** [comment] 2020-07-08 13:20
confirmed to be fixed, in #3951 
Feel free to open a new issue if you face any other problem

**Closed by LabhanshAgrawal** 2020-07-08 13:20 UTC
