### ISSUE TITLE
ssh on Windows with hyper-terminal meets a crash

### ISSUE THREAD

**Issue by Chr1s-T** [vercel/hyper#3719] opened 2019-06-04 12:48 UTC
## I dont know how to explain this problem. All I got know, is that my terminal turning into a ugly interface when I SSH to a server. Besides, After I use vim, expecially the tmux, the whole terminal crushed into a shit, the terminal becomes useless in this case. Although there are many themes, and I have tried them for many times, it looks like useless. Who can help to solve this problem? I believe that many Windows users have been bothering with this problem all the time, and prey for a great solusion.

**Comment by andreafalco1991** [comment] 2019-10-08 13:20
Duplicate of #3797

**Closed** 2021-10-04 05:22 UTC
