### ISSUE TITLE
plugins decorating term has been disabled because of a plugin crash

### ISSUE THREAD

**Issue by yuis-ice** [vercel/hyper#5257] opened 2021-01-25 04:06 UTC
- [x ] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x ] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: windows 10 pro 10.0.19041 N/A Build 19041
- **Hyper.app version**: 3.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [hyper.js](https://gist.github.com/yuis-ice/d1bcd2d9c91e778291caf88ff1cfc665)
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: *unable to open devtool on the crashed hyper window, ctrl-shift-I not working*
- **The issue is reproducible in vanilla Hyper.app**: no. it have plugins

## Issue

"plugins decorating term has been disabled because of a plugin crash" error on Windows 10 hyper. 

I've been using hyper for a year or so, but yesterday and today the crash happened from nowhere. Not like recently I installed a new plugin on it or updated to the beta or anything. 

I cannot access to the crashed hyper window at all, for example ctrl-shift-R to reload not works. 

The crash happened to me two times. When the first one, I have no idea how, just my entire monitor screen
once or twice blinked, after that hyper became a dead. Perhaps windows's background update or something?? When the second one, I was installing a new version of NVIDIA driver onto windows. while that installing procedure, you know, once or twice the screen blinked, it's understandable since it's graphic stuff updating, then the opened hyper windows died. 

![https://yuis.xsrv.jp/images/ss/ShareX_ScreenShot_ed31abc2-9af9-4119-84ce-417d828c2010.png](https://yuis.xsrv.jp/images/ss/ShareX_ScreenShot_ed31abc2-9af9-4119-84ce-417d828c2010.png)

**Comment by LabhanshAgrawal** [comment] 2021-02-03 16:29
Did it happen again since then? maybe it's graphics issue, if you face this again try once with webgl renderer disabled or with the latest build.

**Comment by LabhanshAgrawal** [comment] 2021-02-03 16:30
some plugin might've been updated too, also check after disabling plugins

**Comment by yuis-ice** [comment] 2021-02-04 01:38
So far not yet happened again. okay I will try webgl renderer/disabling plugins

**Comment by LabhanshAgrawal** [comment] 2021-02-08 05:53
closing this for now, reopen if you face it again or have some steps to reproduce it.

**Closed by LabhanshAgrawal** 2021-02-08 05:53 UTC

**Comment by tayzlor** [comment] 2022-04-22 08:47
Seems linked https://github.com/henrikdahl/hyper-tabs-enhanced/issues/37
