### ISSUE TITLE
How do I use the new hyper cli to install plugins and themes?

### ISSUE THREAD

**Issue by stereokai** [vercel/hyper#2849] opened 2018-04-17 09:39 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Win 10
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/stereokai/b1ca15587030a1013e4172d1f2b076ec
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue

How do I use the new hyper cli to install plugins and themes?

When I try the command `hyper`, it is not available in the path. I tried running `hyper i <plugin name>` from within the folder containing Hyper.exe, but it just opened another terminal instance in the already opened terminal.

It said on the blog that this command came bundled with version 2.0.0. Would appreciate some information on how to use it.

Thanks 💐

**Comment by albinekb** [comment] 2018-04-17 10:54
Have you tried rebooting your PC? 😊 
I think this is a duplicate of https://github.com/zeit/hyper/issues/2823

**Comment by stereokai** [comment] 2018-04-17 11:14
How did it not come up in the search >_>

Anyway, it's not even a matter of path variable. If I run `hyper i someplugin` like I wrote, a new terminal is opened inside the current terminal, instead of running the install command.

**Comment by stereokai** [comment] 2018-04-18 09:32
Already tried that :(

**Comment by chabou** [comment] 2018-04-19 12:30
@stereokai Are you trying to install plugin from WSL?

**Comment by stereokai** [comment] 2018-04-19 16:45
Nope. I trying to run the command from a Powershell instance of Hyper

**Comment by eberfreitas** [comment] 2018-06-08 05:03
Having the same problem. Any fixes?

**Comment by zhaobenx** [comment] 2018-06-08 14:45
Same problem on windows.

**Comment by hacktivist123** [comment] 2018-06-13 21:33
Hey Guys, You Might Want to run hyper as administrator and then try re-installing the plugin. It should definitely work

**Comment by AtariVSega** [comment] 2018-07-09 18:29
thanks @hacktivist123 that really helped!

**Comment by hacktivist123** [comment] 2018-07-10 07:50
My pleasure @AtariVSega

**Comment by jukefr** [comment] 2018-08-13 18:29
@albinekb rebooting did work but maybe there should be a visual warning at some point in the installation process or a prompt asking to reboot.

**Comment by larsgrah** [comment] 2018-10-06 00:53
I have a similar issue on linux, my setup is:

Installed hyper through the AppImage
When I try to install a plugin it just starts another instance of hyper

Tried rebooting already

I am running on Solus

**Comment by bryton-jay-smith** [comment] 2019-04-10 08:02
This happened to me - it means that your PATH variable is directed to "%appdata%/local/", but it needs to be set to "%appdata%/local/appXXX/Local\hyper\app-2.1.2\resources\bin\hyper.cmd" in order for it to accept command line options

**Comment by Nepoxx** [comment] 2019-11-18 19:22
If you install `hyper` from the AUR in Arch Linux, the executable you need to use is  `/usr/lib/hyper/resources/bin/hyper`

**Comment by serverguyken** [comment] 2020-02-19 04:05
@stereokai  You don't need to restart your system, just run Hyper as an administrator and run the command you are trying to, that worked for me.

**Comment by stereokai** [comment] 2020-05-10 12:35
Run as administrator is not a friendly solution, why should a simple npm install (that's what hyper plugins are after all) require admin privilege to install?

**Comment by TheHaricover** [comment] 2020-07-18 18:00
Happened to me too.
Still happening when I'm launching Hyper in root (either by adding "zensu" in front of the command from the launcher or by trying to launch Hyper myself with a term, always with "zensu" ofc).
If someone have an idea, I'm taking it :)
In the meantime I'll dig where I can.

**Comment by TheHaricover** [comment] 2020-07-19 12:33
I tried the latest build, Hyper-3.1.0-canary.4.AppImage, and it didn't work, but differently (it wants --no-sandbox now when being launch with sudo, and it write more text when launching a new hyper term when I'm typing "hyper i")

**Closed** 2021-02-24 19:41 UTC
Labels: ⌨️ CLI tool, 🖼 Platform: Windows

**Comment by JeroenVos106** [comment] 2023-12-19 18:48
> @stereokai You don't need to restart your system, just run Hyper as an administrator and run the command you are trying to, that worked for me.

Worked for me too!!

**Comment by Tardis07** [comment] 2026-01-22 02:46
> I tried the latest build, Hyper-3.1.0-canary.4.AppImage, and it didn't work, but differently (it wants --no-sandbox now when being launch with sudo, and it write more text when launching a new hyper term when I'm typing "hyper i")

Same problem here. Have you fixed it?
