### ISSUE TITLE
I've got blurry text in hyper.

### ISSUE THREAD

**Issue by sharmachinmay** [vercel/hyper#4746] opened 2020-07-16 18:36 UTC
I'm using latest version of hyper and getting very blurry text.
![Annotation 2020-07-16 235109](https://user-images.githubusercontent.com/67503180/87709075-56607900-c7c1-11ea-985b-b97dfe69f78a.jpg)
Please help me, it's getting very annoying.

**Comment by LabhanshAgrawal** [comment] 2020-07-16 18:38
try the latest [ci build](https://github.com/vercel/hyper/actions/runs/170038990)

**Comment by LabhanshAgrawal** [comment] 2021-02-05 11:16
duplicate of #3684

**Closed by LabhanshAgrawal** 2021-02-05 11:16 UTC
