### ISSUE TITLE
Macos Big Sur 11.5 Has broken hyper and it is not working

### ISSUE THREAD

**Issue by ahpegasus** [vercel/hyper#5800] opened 2021-07-26 16:20 UTC
- [x] Your Hyper.app version is **3.1.1**. Please verify your using the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate
---
- **Any relevant information from devtools?** _(CMD+OPTION+I on macOS, CTRL+SHIFT+I elsewhere)_:

- **Is the issue reproducible in vanilla Hyper.app?**

## Issue

---

- **Hyper version**: undefined "3.1.1"
- **OS ARCH VERSION:** darwin x64 20.6.0
- **Electron:** 13.1.6  **LANG:** undefined
- **SHELL:** /bin/bash   **TERM:** undefined
<details><summary><strong>.hyper.js contents</strong></summary>

```json
{
  "updateChannel": "stable",
  "fontSize": 13,
  "fontFamily": "\"Fira Code\", Menlo, \"DejaVu Sans Mono\", Consolas, \"Lucida Console\", monospace",
  "fontWeight": "normal",
  "fontWeightBold": "bold",
  "lineHeight": 1,
  "letterSpacing": 0,
  "cursorColor": "rgba(248,28,229,0.8)",
  "cursorAccentColor": "#000",
  "cursorShape": "BLOCK",
  "cursorBlink": false,
  "foregroundColor": "#fff",
  "backgroundColor": "#000",
  "selectionColor": "rgba(248,28,229,0.3)",
  "borderColor": "#333",
  "css": "",
  "termCSS": "",
  "showHamburgerMenu": "",
  "showWindowControls": "",
  "padding": "12px 14px",
  "colors": {
    "black": "#000000",
    "red": "#C51E14",
    "green": "#1DC121",
    "yellow": "#C7C329",
    "blue": "#0A2FC4",
    "magenta": "#C839C5",
    "cyan": "#20C5C6",
    "white": "#C7C7C7",
    "lightBlack": "#686868",
    "lightRed": "#FD6F6B",
    "lightGreen": "#67F86F",
    "lightYellow": "#FFFA72",
    "lightBlue": "#6A76FB",
    "lightMagenta": "#FD7CFC",
    "lightCyan": "#68FDFE",
    "lightWhite": "#FFFFFF"
  },
  "shell": "/usr/local/bin/zsh",
  "shellArgs": [
    "--login"
  ],
  "env": {},
  "bell": "SOUND",
  "copyOnSelect": false,
  "defaultSSHApp": true,
  "quickEdit": false,
  "macOptionSelectionMode": "vertical",
  "webGLRenderer": false,
  "activeTab": "🚀"
}
```
</details>
<details><summary><strong>plugins</strong></summary>

```json
{
  "plugins": [
    "hyper-font-ligatures",
    "hyper-one-dark",
    "hyper-search",
    "hyper-pane",
    "hypercwd",
    "hyper-active-tab",
    "hyperline",
    "hyperpower"
  ],
  "localPlugins": []
}
```
</details>

**Comment by alimehasin** [comment] 2021-07-27 12:52
I have the same problem, I have just installed the hyper using homebrew and when I run it macOS tell me

> “Hyper” can’t be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information.

I am running macOS big sur v11.5

**Comment by LabhanshAgrawal** [comment] 2021-07-27 13:09
duplicate of #5779

**Closed by LabhanshAgrawal** 2021-07-27 13:09 UTC

**Comment by tylerdev719** [comment] 2021-08-06 12:28
Any updates on the fix for this issue on Mac's new Big Sur update yet?

**Comment by LabhanshAgrawal** [comment] 2021-08-06 15:34
https://github.com/vercel/hyper/issues/5779#issuecomment-883891711
