### ISSUE TITLE
I can't type anything. Black Screen!

### ISSUE THREAD

**Issue by pablogrippo** [vercel/hyper#6222] opened 2022-01-06 20:41 UTC
- [ ] Your Hyper.app version is **3.1.4**. Please verify your using the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [ ] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate
---
- **Any relevant information from devtools?** _(CMD+OPTION+I on macOS, CTRL+SHIFT+I elsewhere)_:

- **Is the issue reproducible in vanilla Hyper.app?**

## Issue

I can't type anything. It is like blocked and it remains all black and nothing happen. 

---

- **Hyper version**: undefined "3.1.4"
- **OS ARCH VERSION:** darwin x64 21.2.0
- **Electron:** 13.2.3  **LANG:** undefined
- **SHELL:** /bin/zsh   **TERM:** undefined
<details><summary><strong>.hyper.js contents</strong></summary>

```json
{
  "updateChannel": "stable",
  "fontSize": 16,
  "fontFamily": "Menlo, \"DejaVu Sans Mono\", Consolas, \"Lucida Console\", monospace",
  "fontWeight": "normal",
  "fontWeightBold": "bold",
  "lineHeight": 1,
  "letterSpacing": 0,
  "cursorColor": "rgba(248,28,229,0.8)",
  "cursorAccentColor": "#000",
  "cursorShape": "BLOCK",
  "cursorBlink": false,
<img width="664" alt="Captura de Pantalla 2022-01-06 a la(s) 17 40 07" src="https://user-images.githubusercontent.com/2981218/148448757-d019939e-4eb8-4c8f-b379-28d0dfa2b715.png">

  "foregroundColor": "#fff",
  "backgroundColor": "#000",
  "selectionColor": "rgba(248,28,229,0.3)",
  "borderColor": "#333",
  "css": "",
  "termCSS": "",
  "showHamburgerMenu": "",
  "showWindowControls": "",
  "padding": "12px 14px",
  "colors": {
    "black": "#000000",
    "red": "#C51E14",
    "green": "#1DC121",
    "yellow": "#C7C329",
    "blue": "#0A2FC4",
    "magenta": "#C839C5",
    "cyan": "#20C5C6",
    "white": "#C7C7C7",
    "lightBlack": "#686868",
    "lightRed": "#FD6F6B",
    "lightGreen": "#67F86F",
    "lightYellow": "#FFFA72",
    "lightBlue": "#6A76FB",
    "lightMagenta": "#FD7CFC",
    "lightCyan": "#68FDFE",
    "lightWhite": "#FFFFFF"
  },
  "shell": "",
  "shellArgs": [
    "--login"
  ],
  "env": {},
  "bell": "SOUND",
  "copyOnSelect": false,
  "defaultSSHApp": true,
  "quickEdit": false,
  "macOptionSelectionMode": "vertical",
  "webGLRenderer": true
}
```
</details>
<details><summary><strong>plugins</strong></summary>

```json
{
  "plugins": [
    "verminal"
  ],
  "localPlugins": []
}
```
</details>

**Comment by LabhanshAgrawal** [comment] 2022-01-07 06:07
Duplicate of #6083

**Closed by LabhanshAgrawal** 2022-01-07 06:07 UTC
