### ISSUE TITLE
Lost rounded corners on macOS High Sierra

### ISSUE THREAD

**Issue by kajka** [vercel/hyper#2287] opened 2017-09-26 12:54 UTC
Hi there!

After updating the system to 10.13 High Sierra appeared a problem with the application window. The application window looks fine with the default theme:

![screen shot 2017-09-26 at 11 21 38](https://user-images.githubusercontent.com/2843796/30861213-528efba4-a2ca-11e7-930c-cfab56eef47b.png)

However, when I'm apply my theme, the Hyper window loses its rounded corners:

<img width="1044" alt="screen shot 2017-09-26 at 14 53 16" src="https://user-images.githubusercontent.com/2843796/30861259-7a23c80c-a2ca-11e7-9a4f-08928c2c9952.png">

Here is also my theme: https://gist.github.com/kajka/b8bd99c07e788b14f68954ca883c9e69
I use it as local plugin.

---
OS: macOS 10.13 High Sierra
Hyper version: 1.4.8/2.0.4
My config file: https://gist.github.com/kajka/d333f948c65177a6300a25eb3425e427

**Comment by rohmanhm** [comment] 2017-09-26 13:41
Hi, I'm using Ubuntu 16.04 and didn't get rounded border too.

**Comment by albinekb** [comment] 2017-09-26 14:45
@rohmanhm are you getting them with Hyper on `stable`(1.4.x) and/or `canary`(2.x.x)?

**Comment by rohmanhm** [comment] 2017-09-26 15:06
@albinekb Yeah.

![image](https://user-images.githubusercontent.com/7524911/30867648-c5899f2e-a306-11e7-8da3-1ee952f476e3.png)

Ubuntu 16.04
Hyper 2.0.4 (stable)

**Comment by MAPESO** [comment] 2017-09-26 15:15
@albinekb I just updated to the version of mac os high sierra, but this problem does not present it 🤔
as you can see there are rounded corners. @rohmanhm I'll take a look at your problem.
![os](https://user-images.githubusercontent.com/16585386/30868093-4cb7228c-a2a3-11e7-9826-d3cd7a357f17.png)

![hyper](https://user-images.githubusercontent.com/16585386/30868099-51bac752-a2a3-11e7-9076-277c83b7b267.png)

**Comment by ideaweb** [comment] 2017-09-26 15:45
For me its broken with blurred background in High Sierra e.g. with "hyper-transparent > View > Vibrancy > Dark" or with "hyper-simple-vibrancy".

![screen shot 2017-09-26 at 17 43 06](https://user-images.githubusercontent.com/1529649/30869731-380cf8d6-a2e2-11e7-8e32-4b2d8db3b7d0.png)
![screen shot 2017-09-26 at 17 43 13](https://user-images.githubusercontent.com/1529649/30869729-37ee9cd8-a2e2-11e7-986e-9517939e407c.png)

**Comment by ideaweb** [comment] 2017-09-26 15:48
For me its broken with blurred background in High Sierra e.g. with "hyper-transparent > View > Vibrancy > Dark" or with "hyper-simple-vibrancy".

![screen shot 2017-09-26 at 17 48 08](https://user-images.githubusercontent.com/1529649/30869982-ed6ac302-a2e2-11e7-83bf-10a51969c96e.png)
![screen shot 2017-09-26 at 17 48 19](https://user-images.githubusercontent.com/1529649/30869981-ed688060-a2e2-11e7-8dd0-267d159b35a3.png)

**Comment by kajka** [comment] 2017-09-26 15:51
@MAPESO I have no idea what happened to my theme or configuration file (like I said they work completely fine on previous version of macOS; I noticed now that I did not have in config file line that corresponding to channel update before; I can only suspect that the line appeared after updating to the Canary version).

I modified my theme based on the theme created by @henrikdahl . Now everything works fine.

Theme file looks like so: https://gist.github.com/kajka/9e00fbfc787cc05d032e7d2cd443b4b6

![screen shot 2017-09-26 at 17 44 11](https://user-images.githubusercontent.com/2843796/30869794-60e6c516-a2e2-11e7-80fe-1c7c528ca7e5.png)

OFFTOPIC
I also managed to fix bug (described here: https://github.com/henrikdahl/hyper-statusline/issues/61 ) that occurred at the beginning of branch 1.4 and the hyper-statusline plug-in. I moved the plugin to the `local` directory and downloaded the necessary modules (`tildify after-all-results`) into the `node_modules` directory. For a reason unknown to me, the plugin does not work properly when it is in the `node_modules` directory.

**Comment by albinekb** [comment] 2017-09-26 16:02
If I'm reading this correct, you mean that this is no issue with 2.0 (rounded corners) and was just a config issue? So we can close this one? 🙉  @kajka

**Comment by MAPESO** [comment] 2017-09-26 16:17
@This was setup error, we can rule out that this error does not belong to Hyper 2.0.3 or 1.4.7

**Comment by ideaweb** [comment] 2017-09-26 16:24
Currently i have no idea, i just updated to High Sierra with same config and then I noticed that rounded corners are gone. I updated 1.4 to 2.0 in hope that it helps, but this is not true. For me its not a big issue, only nice2have.

**Comment by kajka** [comment] 2017-09-26 16:28
@albinekb @ideaweb No it wasn't config issue. My old theme still does not work properly. I had to rewrite it. As you can see above, many people also have this problem (check @ideaweb posts). On MacOS Sierra everything worked excellently.

My problem with the configuration file was that missing comma (again thank you @albinekb for help). I have not modified the configuration file since version 1.2. It seems to me that the missing comma is due to an upgrade to Canary 2.0.x (Hyper must add some line into config file about the update channel).

**Comment by albinekb** [comment] 2017-09-26 16:29
I understand now @kajka @ideaweb, thanks for clarifying 👍  It's a general issue with rounded corners & High Sierra, that this issue tracks.

**Comment by kajka** [comment] 2017-09-26 16:32
@albinekb That's correct.

**Comment by MAPESO** [comment] 2017-09-26 16:52
@ideaweb you can try this theme: **hypermaterial-vibrancy**

I need to rule out that the problem is the theme 😄

**Comment by mdeboer** [comment] 2017-09-26 21:11
I tried it with my fork of a theme [hyperterm-dark-fusion-vibrancy](https://github.com/mdeboer/hyperterm-dark-fusion-vibrancy) where I implemented vibrancy and it causes the same problem.

**Comment by MAPESO** [comment] 2017-09-26 23:50
@rohmanhm Hyper is built on electron, and electron uses the native look of operating system windows. That's why you cannot see rounded edges as in **macOS** 💔

**Comment by MAPESO** [comment] 2017-09-26 23:57
@mdeboer  Maybe it is a subject of incompatibility by the plugin.

**Comment by MAPESO** [comment] 2017-09-27 00:10
@mdeboer Could you tell me your version of Hyper and operating system? 

I just applied the theme and it works normal 🤔
![screen shot 2017-09-26 at 190517](https://user-images.githubusercontent.com/16585386/30889781-5f6a8ca2-a2ee-11e7-803f-1cce02ac945b.png)

**Comment by MAPESO** [comment] 2017-09-27 00:13
@albinekb I just tried this hyper-transparent topic in the hyper **version 2.0.4**

and I return to the subject by defectto. With this we can confirm that the plguin is incompatible with version 2.0.4

**Comment by rohmanhm** [comment] 2017-09-27 00:15
@MAPESO but all my app is rounded, also chrome.

![image](https://user-images.githubusercontent.com/7524911/30889886-98387dc2-a353-11e7-8faf-76b7c7d5d42f.png)

Look that rounded

**Comment by rohmanhm** [comment] 2017-09-27 00:16
Compared Google Chrome and Hyper.

![image](https://user-images.githubusercontent.com/7524911/30889925-d17009f2-a353-11e7-8bab-674fd627b99e.png)

**Comment by MAPESO** [comment] 2017-09-27 00:20
@rohmanhm I did the tests on my computer but I got the same effect as yours

![line](https://user-images.githubusercontent.com/16585386/30889987-929972e0-a2ef-11e7-9915-a2ce13f097bd.png)

**Comment by MAPESO** [comment] 2017-09-27 00:22
@rohmanhm I do not know how it is that chrome causes the effect of rounded edges. But we will investigate the problem 😸

**Comment by mdeboer** [comment] 2017-09-27 00:54
@MAPESO I use High Sierra but on your screenshot you don't have rounded corners either 😉  The issue might be related to Electron though, at least if it's related to vibrancy. I modded Atom to use vibrancy and it's also square.

I'll play with the theme some more, I've been working on so many things I'm afraid I'll mix em up 😉

**Comment by MAPESO** [comment] 2017-09-27 01:14
@mdeboer My wallpaper has confused me, I thought the edges were rounded 😅
for the next I will do the tests on a white background : )

**Comment by ideaweb** [comment] 2017-09-27 07:53
I tested "hyperterm-dark-fusion-vibrancy" and rounded corners are gone too. 

![screen shot 2017-09-26 at 17 48 19](https://user-images.githubusercontent.com/1529649/30901646-f8f8a960-a368-11e7-9c88-f2096ee7a590.png)

Same for hyper-firewatch.

![screen shot 2017-09-27 at 09 51 27](https://user-images.githubusercontent.com/1529649/30901793-7efe3cd2-a369-11e7-9c4d-21a454441de9.png)

Without both plugins rounded corners are back.

![screen shot 2017-09-27 at 09 52 19](https://user-images.githubusercontent.com/1529649/30901852-a27b3246-a369-11e7-997a-a0705248ff52.png)

**Comment by mdeboer** [comment] 2017-09-27 13:18
It is because the HTML canvas doesn't have rounded corners, you can see it when you open the developer tools in the elements tab and hover the html node. I think setting the `border-radius` to 5px would give more or less the same look.

I'm not sure of the inner workings of electron but maybe setting a `overflow: hidden` like option would fix it as well?

**Comment by albinekb** [comment] 2017-09-27 13:25
The problem with that @mdeboer is that transparency is not supported in windows (without disabling gpu acceleration), same for most linux distros..

**Comment by mdeboer** [comment] 2017-09-27 13:48
@albinekb vibrancy is a MacOS only function but as this also happens with non-transparent themes, this issue has nothing to do with transparency.

**Comment by mdeboer** [comment] 2017-09-28 11:50
@MAPESO check out this issue in the electron repo: https://github.com/electron/electron/issues/8305

**Comment by alberto2000** [comment] 2017-11-09 22:43
Still no way to get rounded corners with vibrancy on MacOS High Sierra?

**Comment by mdeboer** [comment] 2017-11-09 23:28
@alberto2000 see the electron issue linked above, hasn't been fixed yet and rounded corners are not working yet. This is likely a bug in electron and not a bug in hyper 😉

**Comment by controversial** [comment] 2018-07-16 21:04
This is fixed for me on the macOS 10.14 Mojave beta

**Closed** 2020-07-04 18:51 UTC
Labels: 🐛 Type: Bug, 👆 Is Upstream

**Comment by jcklpe** [comment] 2022-09-08 00:22
Is there a way to get rid of rounded corners if I don't like how it plays with my theme?
