### ISSUE TITLE
Nano editor doesn't close when ssh tunnel killed

### ISSUE THREAD

**Issue by silverlight513** [vercel/hyper#493] opened 2016-07-29 08:11 UTC
I SSH'd into a server and opened up a log file in nano. I then locked the laptop and left it over night. When looking at the terminal this morning nano was still open but the text to say the connection has been closed was over the top of nano. I had to return multiple lines to get past nano.

(can't provide screenshot because of sensitive information)

**Comment by LabhanshAgrawal** [comment] 2021-10-04 06:34
expected behaviour
nano, less, tmux etc. are curses applications and they need to send the `endwin` sequence while closing
Since you were using ssh, and the connection broke, these sequences were never received and so terminal content from before didn't restore.
If needed, you can just do a `ls | less` and exit `less` using `q` and it will restore the terminal.

**Closed by LabhanshAgrawal** 2021-10-04 06:34 UTC
Labels: help wanted, 🤯  Type: Compatibility
