### ISSUE TITLE
Uninstalling on Windows does not remove right click context menu entry

### ISSUE THREAD

**Issue by ryancole** [vercel/hyper#1242] opened 2016-12-16 06:23 UTC
Uninstalling Hyper, on Windows, does not remove the context menu (right click) entry.

**Comment by Speiser** [comment] 2016-12-17 14:13
Open `\HKEY_CLASSES_ROOT\Directory\Background\shell\` (with regedit) and remove the `Hyper` folder.

**Comment by fyears** [comment] 2017-02-17 11:41
It seems that it's fixed in version 1.2.1.

I downloaded the latest Windows version today, and **uninstall it from control panel**, the context goes away.

**Comment by secondfry** [comment] 2017-02-26 10:33
Can confirm as **not** fixed in 1.2.1 (Windows 10, latest updates, Hyper 1.2.1).

**Comment by b-ggs** [comment] 2017-07-30 16:00
This is still not fixed in 1.3.3.

**Comment by sirberus** [comment] 2018-05-10 19:19
Still not fixed... Seems small but it leaves a bad taste in my mouth.

**Comment by kamil445** [comment] 2018-07-14 14:44
For me worked: HKEY_LOCAL_MACHINE\SOFTWARE\Classes\LibraryFolder\background\shell\git_shell and \git_gui

**Comment by BruceBayne** [comment] 2018-12-14 23:46
They uninstaller do nothing, and leave lots of garbage in registry, thats why i love portable soft,

Try open regedit and just search for 5KPlayer after uninstalling, and you will be shocked

**Comment by shaneknysh** [comment] 2019-02-19 21:40
may be a duplicate of #3090

**Comment by LabhanshAgrawal** [comment] 2020-06-26 15:36
Tested on latest canary, seems to be fixed, no results on searching 'Open Hyper here' in registry after uninstall.

**Closed by LabhanshAgrawal** 2020-06-26 15:36 UTC
Labels: help wanted, 🐛 Type: Bug, 🖼 Platform: Windows
