### ISSUE TITLE
mac 12.0.1 can't see anythin

### ISSUE THREAD

**Issue by JokerLigang** [vercel/hyper#6112] opened 2021-11-19 03:55 UTC
- [ ] Your Hyper.app version is **3.1.4**. Please verify your using the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [ ] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate
---
- **Any relevant information from devtools?** _(CMD+OPTION+I on macOS, CTRL+SHIFT+I elsewhere)_:

- **Is the issue reproducible in vanilla Hyper.app?**

## Issue

---

- **Hyper version**: undefined "3.1.4"
- **OS ARCH VERSION:** darwin x64 21.1.0
- **Electron:** 13.2.3  **LANG:** undefined
- **SHELL:** /bin/zsh   **TERM:** undefined
<details><summary><strong>.hyper.js contents</strong></summary>

```json
{
  "hyperTransparentDynamic": {
    "alpha": 0.5
  },
  "updateChannel": "stable",
  "fontSize": 18,
  "fontFamily": "Menlo, \"DejaVu Sans Mono\", Consolas, \"Lucida Console\", monospace",
  "fontWeight": "normal",
  "fontWeightBold": "bold",
  "lineHeight": 1,
  "letterSpacing": 0,
  "cursorColor": "rgba(248,28,229,0.8)",
  "cursorAccentColor": "#000",
  "cursorShape": "BLOCK",
  "cursorBlink": false,
  "foregroundColor": "#fff",
  "backgroundColor": "#C7C329",
  "selectionColor": "rgba(248,28,229,0.3)",
  "borderColor": "#333",
  "css": "",
  "termCSS": "",
  "showHamburgerMenu": "",
  "showWindowControls": "",
  "padding": "12px 14px",
  "colors": {
    "black": "#000000",
    "red": "#C51E14",
    "green": "#1DC121",
    "yellow": "#C7C329",
    "blue": "#0A2FC4",
    "magenta": "#C839C5",
    "cyan": "#20C5C6",
    "white": "#C7C7C7",
    "lightBlack": "#686868",
    "lightRed": "#FD6F6B",
    "lightGreen": "#67F86F",
    "lightYellow": "#FFFA72",
    "lightBlue": "#6A76FB",
    "lightMagenta": "#FD7CFC",
    "lightCyan": "#68FDFE",
    "lightWhite": "#FFFFFF"
  },
  "shell": "",
  "shellArgs": [
    "--login"
  ],
  "env": {},
  "bell": "SOUND",
  "copyOnSelect": false,
  "defaultSSHApp": true,
  "quickEdit": false,
  "macOptionSelectionMode": "vertical",
  "webGLRenderer": true
}
```
</details>
<details><summary><strong>plugins</strong></summary>

```json
{
  "plugins": [
    "hypercwd",
    "hyper-search",
    "hyperpower",
    "hyper-tabs-autohide",
    "hyper-transparent-dynamic",
    "verminal",
    "hyper-hypest"
  ],
  "localPlugins": []
}
```
</details>

**Comment by LabhanshAgrawal** [comment] 2021-11-19 04:00
Can you please also provide the output from devtools and `hyper -v`?

**Comment by DaudiMuriu** [comment] 2021-11-19 07:52
<img width="1792" alt="Screenshot 2021-11-19 at 10 51 29 AM" src="https://user-images.githubusercontent.com/33577405/142585706-ddc84dc8-bf63-4feb-939a-530a1c4eb440.png">
like you can’t  see anything completely

**Comment by thejoshuabowers** [comment] 2021-11-22 12:16
I think i'm having the same issue. It opens, then if i click any button, it goes blank.

**Comment by thejoshuabowers** [comment] 2021-11-22 12:24
found the solution for me. https://github.com/vercel/hyper/issues/6083 Hope this helps. Had to remove the font family line from index.js

**Comment by LabhanshAgrawal** [comment] 2022-01-07 06:07
Duplicate of #6083

**Closed by LabhanshAgrawal** 2022-01-07 06:07 UTC
