### ISSUE TITLE
Hyper windows not clearing properly

### ISSUE THREAD

**Issue by jacekv** [vercel/hyper#3664] opened 2019-05-13 07:21 UTC
- [x] Your Hyper.app version is **3.0.2**.
  - [x] I have searched the of this repo and believe that this is not a duplicate

  - **Is the issue reproducible in vanilla Hyper.app?**
Have no plugins installed!

## Issue

I am going to describe the problem based on using Nano. This problem might also be happening with tools who use the whole screen.

If you open a text file using Nano, the lower part of the hyper window is showing the Shortcuts. 
![ok](https://user-images.githubusercontent.com/14347871/57601044-cb03ac00-755b-11e9-88be-ffbd16fa064f.PNG)

As exit Nano, the lower part of the screen is not cleared: 
![notok](https://user-images.githubusercontent.com/14347871/57601155-069e7600-755c-11e9-9f33-b46dce846bf8.PNG)

CTRL+L does not help. Only if I click into the hyper window, the lower part gets cleared. Another way to test it is by typing a number of commands to fill the windows and try to clear it by using CTRL+L. The result is:
![notok2](https://user-images.githubusercontent.com/14347871/57601283-63019580-755c-11e9-81b4-cb4e60182807.PNG)

 - **Hyper version**:  "3.0.2"

 - **OS ARCH VERSION:** win32 x64 10.0.17763
 - **Electron:** 3.1.3  **LANG:** undefined
 - **SHELL:** undefined   **TERM:** undefined

  <details>
    <summary><strong> ~/.hyper.js contents</strong></summary>
      <pre>
        <code>
          updateChannel: 'stable',
    fontSize: 12,
    fontFamily: 'Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',
    fontWeight: 'normal',
    fontWeightBold: 'bold',
    lineHeight: 1,
    letterSpacing: 0,
    cursorColor: 'rgba(248,28,229,0.8)',
    cursorAccentColor: '#000',
    cursorShape: 'BLOCK',
    cursorBlink: false,
    foregroundColor: '#fff',
    backgroundColor: '#000',
    selectionColor: 'rgba(248,28,229,0.3)',
    borderColor: '#333',
    css: '',
    termCSS: '',
    showHamburgerMenu: '',
    showWindowControls: '',
    padding: '12px 14px',
    colors: {
      black: '#000000',
      red: '#C51E14',
      green: '#1DC121',
      yellow: '#C7C329',
      blue: '#0A2FC4',
      magenta: '#C839C5',
      cyan: '#20C5C6',
      white: '#C7C7C7',
      lightBlack: '#686868',
      lightRed: '#FD6F6B',
      lightGreen: '#67F86F',
      lightYellow: '#FFFA72',
      lightBlue: '#6A76FB',
      lightMagenta: '#FD7CFC',
      lightCyan: '#68FDFE',
      lightWhite: '#FFFFFF',
    },
    shell: 'C:\\Windows\\System32\\bash.exe',
    shellArgs: ['--login'],
    env: {},
    bell: 'SOUND',
    copyOnSelect: false,
    defaultSSHApp: true,
    quickEdit: false,
    macOptionSelectionMode: 'vertical',
    webGLRenderer: true,
  },
  plugins: [],
  localPlugins: []
        </code>
      </pre>
  </details>

**Comment by kareltdlg** [comment] 2019-05-13 18:28
I have exactly the same issue. That started to happen to me in hyper version 3.0.0. I frequently use nano editor and this is very annoying.

**Comment by rodrigocaus** [comment] 2019-05-14 13:44
Same here. I've reproduced it using nano and htop. CTRL+L or clear command does not help The window cleans with a click on it.

**Comment by Glenn-Jaya** [comment] 2019-05-14 22:19
same here

**Comment by Suhail** [comment] 2019-05-16 20:37
Same issue

**Comment by donjo9** [comment] 2019-05-22 12:49
I have the same problem WIndows 10 Pro 1809

I have noticed if i have the windows filles with text before entering Nano, the bottom is overwriten as expected when i exit Nano

![image](https://user-images.githubusercontent.com/6575408/58175555-ac5e8d00-7ca0-11e9-89f6-72fb72c6c227.png)

![image](https://user-images.githubusercontent.com/6575408/58175574-baaca900-7ca0-11e9-82e3-f25215d4cb32.png)

![image](https://user-images.githubusercontent.com/6575408/58175593-c4cea780-7ca0-11e9-91bb-a83cfc27bb12.png)

**Comment by thireo** [comment] 2019-05-22 13:03
I'm having the same problem. Windows 10 Pro 1803 @ Hyper 3.0.2 (stable)

I've noticed the problem occurs with a simple "ls -l" and a successive "clear". Upon mouseclicking the terminal window, it clears as it should.

![image](https://user-images.githubusercontent.com/25148816/58176330-58ed3e80-7ca2-11e9-9751-3ad1ba1b413d.png)
![image](https://user-images.githubusercontent.com/25148816/58176373-6c000e80-7ca2-11e9-8e0a-5f54de7ac66b.png)

**Comment by galishmann** [comment] 2019-05-24 16:04
same problem

**Comment by galishmann** [comment] 2019-05-24 16:06
But it fix by clicking left mouse button on window.

**Comment by ajmeraaxesh** [comment] 2019-05-28 05:57
Yes same workaround. Have to click on the unclear area

**Comment by jacekv** [comment] 2019-05-28 06:04
But I don't want to click into the window to clear it :D I know that in a previous version it worked without clicking the window :)

**Comment by dr3amnightmare** [comment] 2019-06-05 15:49
Similar issue for me. Nano doesn't normally leave anything behind for me, but while editing in nano, I get artifacts of text from above when I get to the end of a file making me think there is more to it than there is. I usually just refresh with CTRL + Shift + R but that's pretty annoying to have to do constantly

**Comment by austinrr** [comment] 2019-06-06 22:27
I've noticed a similar problem, although unrelated to nano.  Sometimes when I use `clear` a portion of the window will not re-paint and I have to adjust hyper's window size or something to force a re-paint.

**Comment by dontsave** [comment] 2019-06-07 18:42
Same issue here. This is the number one thing I'd like fixed in the new WebGL renderer if possible

**Comment by thyarles** [comment] 2019-06-11 19:31
Same issue with a simple "ls *". 

Win 1809 + Hyper 3.0.2 without plugins.

I'd try to add "env: {TERM:'msys'},", but has no effect.

**Comment by thyarles** [comment] 2019-06-11 19:49
I found a workaround that worked for me... I put 

```
// fix window size
windowSize:	[800, 600],
```
on my hyper conf file.

**Comment by donjo9** [comment] 2019-06-12 05:27
That does'nt work for me :(

**Comment by galishmann** [comment] 2019-06-21 16:01
@thyarles  It doesn't work in fullscreen

**Comment by jacob33c** [comment] 2019-07-27 02:55
still having an issue with clear console here too

**Comment by lepfsd** [comment] 2019-07-28 12:08
try ctrl + shift + R

**Comment by jacob33c** [comment] 2019-07-29 00:54
@lepfsd yup that's been working for me thanks!

**Comment by Jonathan0wh** [comment] 2019-08-15 14:18
Same issue here. Windows 10 Pro 1903 and Hyper.js 3.0.2 stable using WebGL. Is there any way to fix it without clicking the window or changing the window size?

**Comment by BernardZhao** [comment] 2019-08-21 01:31
Same issue here as well.

**Comment by makdas** [comment] 2019-08-23 05:49
Ctrl + SHIFT + K (clear buffer)
Ctrl + l (clear to top)

**Comment by MrMikeandike** [comment] 2019-10-06 00:23
Same issue using webGL hyper version 3.0.2. Left clicking clears issue without needing reload. 

Has anyone found any better workarounds than ctrl shift r since august? I was so happy to be done with cmder :(

**Comment by Stanzilla** [comment] 2019-10-16 15:40
@MrMikeandike can you disable the webgl renderer in the config and see if that is besser? Otherwise I can recommend https://github.com/Eugeny/terminus

**Comment by saturnonearth** [comment] 2019-10-16 21:50
> @MrMikeandike can you disable the webgl renderer in the config and see if that is besser? Otherwise I can recommend https://github.com/Eugeny/terminus

Terminus is working great! Thanks.

**Comment by fabienjuif** [comment] 2019-12-18 15:17
Hey folks 👋 

I just tried all the workarounds I saw in this issue and it doesn't work properly for me :
 - disabling webgl renderer
 - adding an alias: `alias clear='clear -T linux'`
 - adding the ENV: 'cygwin' (or ENV: 'msys')

Using the clear commands works, but using the CTRL+L shortcut does not.
When I clicked in the terminal the buffer is cleared as suggested @galishmann 😋

**Comment by Stanzilla** [comment] 2019-12-18 15:21
@fabienjuif yeah, I know :/ So the main problem here is that Hyper is pretty much abandoned by ZEIT and we really can't/won't (at least I won't) do releases until this changes again. This also means no canary builds for people to test, so all I can suggest is trying autogenerated builds from our CI.

**Comment by fabienjuif** [comment] 2019-12-18 15:32
I just downloaded this version and it works 🎉 : https://ci.appveyor.com/project/chabou/hyper-1b303/builds/29628840/artifacts

I just removed all the previous configuration I spoke about in the last comment I did and it works :)
Nice, thank you @Stanzilla :)

And sorry to hear that about this project and ZEIT :(

**Comment by Stanzilla** [comment] 2019-12-18 15:39
Awesome!

**Comment by rohitkrishna094** [comment] 2020-01-07 23:07
Is there a fix for this yet? or ctrl+shift+r is the only work around?

**Comment by thyarles** [comment] 2020-01-08 02:23
> Is there a fix for this yet? or ctrl+shift+r is the only work around?

I stopped using it.

**Comment by rohitkrishna094** [comment] 2020-01-08 02:28
Stopped using hyper u mean? If so are there any alternatives for Windows? Thanks

**Comment by thyarles** [comment] 2020-01-08 03:11
> Stopped using hyper u mean? If so are there any alternatives for Windows? Thanks

Sorry @rohitkrishna094, my bad. I stopped using the version 3.0.2 I wanted to say. I build my own Canary version and everything works fine. To build your version on Windows:

* Install YARN (https://yarnpkg.com/en/docs/install#windows-stable)
* Install NodeJS (https://nodejs.org/en/)
* In a **privileged (as administrator)** powershell, install windows build tools
`yarn global add windows-build-tools`
* Clone the Hyper repository
`git clone https://github.com/zeit/hyper.git`
* Inside the hyper folder, and with a **unprivileged** powershell, install all dependencies
`yarn`
* Build your binarie (it will create an executable inside dist folder)
`yarn run dist`
* Run your new binarie and they will replace the bugged version 3.0.2

![image](https://user-images.githubusercontent.com/1340046/71947356-5e54b600-31ab-11ea-87cc-2cb180e5f8f9.png)

Hope it helps.

**Comment by saturnonearth** [comment] 2020-01-08 06:07
> Stopped using hyper u mean? If so are there any alternatives for Windows? Thanks

I've been using the new Windows Terminal - it's pretty good!

**Comment by Stanzilla** [comment] 2020-01-08 16:54
Otherwise I'd suggest https://github.com/Eugeny/terminus

**Comment by thyarles** [comment] 2020-01-13 18:56
> > Stopped using hyper u mean? If so are there any alternatives for Windows? Thanks
> 
> I've been using the new Windows Terminal - it's pretty good!

I definitely stopped using **Hyper**. I tried **terminus** too, but as well is too slow to open. Then I tried the **Windows Terminal Preview**: faster! Just made some personalizations and everything works great (and fast) now. Thanks. 

RIP **terminus** and **Hyper**.

**Comment by RikoKami** [comment] 2020-03-09 13:36
To clean, use the command `ctrl + shift + k`

**Comment by LabhanshAgrawal** [comment] 2020-07-18 06:34
seems to be fixed in canary

**Closed by LabhanshAgrawal** 2020-07-18 06:34 UTC
Labels: WebGL Renderer
