### ISSUE TITLE
Copying text highlighted text copies background shell but not from vim

### ISSUE THREAD

**Issue by garyx** [vercel/hyper#2429] opened 2017-11-05 14:44 UTC
OS: Ubuntu 17.10
Hyper.app version: 2.1.1 
hyper.js https://gist.github.com/garyx/a6f42942ce64c94f1012a95dc74313e4

I just installed 2.1.1 and I was going through my usual workflow and needed to copy some text from a file. So I opened the file in vim, highlighted what I needed and pressed ctrl+shift+c. Then when I paste the text it seems the text in the clipboard is equivilant to the shell that was in the same area before opening vim. 

Copying from the shell itself works ok it seems. But not from vim for some reason, seems to be a focus issue. This seems to happen in vanilla setup without any plugins enabled.

**Comment by garyx** [comment] 2017-11-06 14:38
I did some more testing, this is an issue in 2.1.0 and 2.0.4 but not in 1.4.8.

**Comment by keichinger** [comment] 2017-11-06 16:19
I can confirm the same issues with `less`. Freshly installed 2.1.1 from 1.4.8.

**Comment by keichinger** [comment] 2017-11-17 13:47
@rauchg @leo Is there anything we can do to help getting this issue resolved? Providing logs or anything like this?

**Comment by soleera** [comment] 2017-12-03 05:05
Same issue with neovim; as soon as the window looses focus the text is deselected.

**Comment by asbjornenge** [comment] 2017-12-05 07:51
I'm seeing the same on MacOS with 2.1.1 😕

**Comment by garyx** [comment] 2017-12-06 13:39
Just installed to test the new 2.0.0 Canary 8 and this is an issue there as well. This is very easy to reproduce, is someone not experiencing this as an issue?

**Comment by insanityfarm** [comment] 2017-12-06 14:22
Also seeing this on macOS. When I switched to Canary a few big issues were fixed for me, but copy-paste was rendered nearly useless. For me this is a very high-priority issue.

**Comment by albinekb** [comment] 2017-12-06 19:28
I can reproduce this issue with the latest `2.0.0-canary.8` release, but in VS Code (which uses the same rendering lib for the terminal part, xterm.js) this issue does not exists. 

That makes me think it's an easy fix, but we need to find why/where it goes wrong. @chabou do you have any idea what the issue could be? 🤔

**Comment by albinekb** [comment] 2017-12-06 19:40
Ok, after more digging it looks like I found the source of the issue. It was introduced somewhere between xterm 2.8 and xterm 2.9 https://github.com/xtermjs/xterm.js/issues/1049

**Comment by bgw** [comment] 2017-12-29 17:05
As a workaround, I have a plugin that will monkey-patch this, along with some other selection-related bugs in xterm.js 2.9.2. All of these bugs have been fixed in xterm 3.x.

The plugin: https://github.com/bgw/hyper-shift-select

[The fix for this bug](https://github.com/bgw/hyper-shift-select/commit/bab113d39a8893e452290b71a9a8728cba0baa1b) would require a single-line change in xterm.js. I'd be happy to submit a patch to xterm.js, but I get the impression that they're not interested in cutting another 2.x release, and I'd personally like to see hyper switch to xterm 3.x sooner rather than later.

**Comment by albinekb** [comment] 2018-01-03 14:28
That sounds reasonable @bgw. @chabou have solved the initial worries with the transparency (by re-rendering the font atlas with transparancy when you change to transparent colors), so it's on track to be shipped as soon as we roll out the kinks and regressions that have been introduced in this huge refactor.

**Comment by garyx** [comment] 2018-01-10 10:10
I just tested the new 2.0.0-Canary.9 and I am glad to say that this copy/paste issue seems to be resolved for me in this new release with the new xterm. It would be good to get other here that ran into this issue to download the newest and confirm here as well.

**Comment by bmihelac** [comment] 2018-01-10 10:21
Confirming, 2.0.0-Canary.9 does not have this issue.

**Comment by LabhanshAgrawal** [comment] 2020-07-06 17:21
Closing as https://github.com/xtermjs/xterm.js/issues/1049 is closed, we're on latest xterm and it's not reproducing on testing with latest canary builds.
Feel free to open a new issue if face any problems

**Closed by LabhanshAgrawal** 2020-07-06 17:21 UTC
Labels: ❣️ Priority: High, 🐛 Type: Bug, 👆 Is Upstream
