### ISSUE TITLE
emojis inside PS1 offset cursor by 1

### ISSUE THREAD

**Issue by aaronatmycujoo** [vercel/hyper#2587] opened 2018-01-11 09:09 UTC
- **OS version and name**: High Sierra 10.13.2 (17C88)
- **Hyper.app version**: Hyper 1.4.8 (stable)

## Issue
If I include an emoji inside PS1 my terminal cursor has an offset of 1.

`export PS1="\w " # works`
`export PS1="\w 🐱" # issue`

Any idea on what to do?

I took a screenshot to show the issue: https://imgur.com/a/Z2yxV

**Comment by albinekb** [comment] 2018-01-11 16:20
Add a space after the emoji, emojis are not monospaced so they can't fit inside a column. If you add a space as "padding" it will look correct 👍 @aaronatmycujoo

**Comment by aaronatmycujoo** [comment] 2018-01-15 08:59
The problem is because of the space. Maybe I didn't explain properly :, )

I made a video: https://streamable.com/sgqww

**Comment by albinekb** [comment] 2018-01-15 11:33
I can't see the error there, maybe someone else can reproduce. Hyper handles emojis like iterm does for me, that's what I expect :)

**Comment by aaronatmycujoo** [comment] 2018-01-15 14:38
I use

```- export PS1="\w - "
+ export PS1="\w 🐱 "```

and here is my album to help demonstrate once again:

https://imgur.com/a/VsRJQ

**Comment by aaronatmycujoo** [comment] 2018-01-15 15:02
Hm that does not seem to help. Screenshots below are on the canary update channel.

I do not think the problem is with your software? If I compare before and after:

https://imgur.com/a/DYySY

This is with an emoji and a space. The emoji seems to take up 2 columns and the cursor does not respects that, but the text does.

You can see how after a carriage return the cursor is off by 1: https://imgur.com/a/0f9b3

Maybe it has something to do with: https://www.youtube.com/watch?v=sTzp76JXsoY

**Comment by Elderry** [comment] 2018-01-24 07:40
I have several ''s in my prompt and this also happened to me. The interest part is, the behavior is different on my Windows build-in Powershell and Powershell Core.

**Comment by Elderry** [comment] 2018-01-24 07:45
shell: 'C:\\Program Files\\PowerShell\\6.0.0\\pwsh.exe'
before input:
![core before input](https://user-images.githubusercontent.com/1892221/35320050-619200f4-011d-11e8-853f-8d6d6aaeb5eb.JPG)
after input:
![core after input](https://user-images.githubusercontent.com/1892221/35320056-67b8eb32-011d-11e8-857e-82c648f44a73.JPG)
shell: 'C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe'
before input:
![before input](https://user-images.githubusercontent.com/1892221/35320075-7c9bb70a-011d-11e8-86d2-76d0b000a3c0.JPG)
after input:
![after input](https://user-images.githubusercontent.com/1892221/35320079-80c5575a-011d-11e8-945e-03ebbeea8ed0.JPG)

**Comment by rikumi** [comment] 2018-01-30 04:32
The problem is that Hyper treats all Unicode characters as half-width character, and forces them to fit in `8.4px` width:

```css
.unicode-node {
    display: inline-block;
    vertical-align: top;
    width: 8.4px;
}
```

Apart from emojis, this problem affects all CJK characters because they are full-width. 

Additionally, when multiple CJK characters appear in sequence, one of the characters is repeated after the last by mistake. For example, paste `あいうえお` into Hyper, they may appear as `あいうえおえ`.

Also, typing in Hyper with CJK input methods will result in a total mess. Hyper will catch some of the letters into the terminal, prevent the input method bar from appearing, bring strange characters after the cursor, and turn the cursor into yellow. Here is an example with a Chinese input method typed `ceshiceshiceshi`. Hyper caught `csiehcsi` into the terminal, turned the cursor yellow, and brought some special glitch (maybe part of a character) right of the cursor. 

Use one of the CJK input methods to reproduce the bug.

<img width="674" alt="qq20180130-122832 2x" src="https://user-images.githubusercontent.com/5051300/35548244-19702184-05b9-11e8-9d0c-29b942e933ae.png">

**Comment by aaronatmycujoo** [comment] 2018-01-30 08:46
Nice write up! So it is possible to detect halfwidth unicode characters and only force those to fit into the 8.4px width? Trying to help solve the problem here but I have no experience with this 😅

**Comment by rikumi** [comment] 2018-01-30 08:53
@aaronatmycujoo

8.4px for half-widths; 16.8px for full-widths.
The font size can be customized, so this number may be generated. You may want to find the code that generated this number and that part of CSS.

Again, please also look into the other bugs I just mentioned apart from this one.

**Comment by rikumi** [comment] 2018-01-31 16:34
There's an NPM package about this: `is-fullwidth-code-point`. Use this to solve the problem.

**Comment by curiouscrusher** [comment] 2018-03-06 15:37
As a halfway hack for my setup I just added a `width: auto !important` to the unicode class.
It's not a great fix, and some emoji still seem to make the terminal rendering a bit funky until you run the command or clear the window.

I seem to have the most issues when using a 🐛 emoji, see the gif below for the odd rendering that occurs when you paste one in. The irony of a bug emoji causing a bug...

```
// custom css to embed in the terminal window
    termCSS: '.unicode-node {width: auto !important;}',
```

![bug-emoji](https://user-images.githubusercontent.com/4745854/37041403-c294bcb0-2121-11e8-9c78-1af87b454091.gif)

**Comment by Stanzilla** [comment] 2018-04-23 01:31
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!

**Comment by Elderry** [comment] 2018-04-23 01:55
I'm afraid that this issue remains in the 2.0 version, at least for the powerline character ``:
Before input anything:
![before](https://user-images.githubusercontent.com/1892221/39103272-65861e16-46dc-11e8-9b9d-40a3159b0f01.JPG)
After input `abc`:
![after](https://user-images.githubusercontent.com/1892221/39103279-7013aee8-46dc-11e8-88b8-6feef87b0319.JPG)

**Comment by Stanzilla** [comment] 2018-04-23 01:56
Thanks for reporting bag!

**Comment by Stanzilla** [comment] 2018-04-23 17:35
@Elderry that looks like https://github.com/xtermjs/xterm.js/issues/1059, right?

**Comment by Elderry** [comment] 2018-04-24 01:37
Nope, I don't think its the same issue. But I can confirm this problem also happens in vscode, so it's fine to make this as an upstream issue.

**Comment by rikumi** [comment] 2018-04-25 02:08
Seems like in Hyper v2 the terminal is rendered in a canvas instead of with CSS. The problem with CJK characters has been fixed.

**Comment by youngboy** [comment] 2018-10-28 11:16
About emoji unicode version and its width problem,
after https://github.com/xtermjs/xterm.js/pull/1714 merge, this issue will be fixed

tested successful in my local build...

**Comment by aaronatmycujoo** [comment] 2018-10-29 09:05
For me the issue has been sovled with 2.1.0-canary.3 🎉

**Comment by LabhanshAgrawal** [comment] 2020-07-06 07:13
Fixed in https://github.com/vercel/hyper/pull/4679

**Closed by LabhanshAgrawal** 2020-07-06 07:13 UTC
Labels: 🐛 Type: Bug, 👆 Is Upstream

**Comment by bitttttten** [comment] 2020-10-07 10:43
I am still hitting this isse in Hyper 3.0.2 on stable and on canary.

```sh
PROMPT='%F{yellow}%/ 👻 %f'
```

Notice the space after the ghost. It appears in hyper like so:

![Screenshot 2020-10-07 at 12 42 51](https://user-images.githubusercontent.com/19930241/95320981-a15acb80-089a-11eb-9a6d-8eb05a0496ca.png)

You can see the ghost is taking up two character spaces. If I replace the ghost with a letter, like `A` you'll get:

![Screenshot 2020-10-07 at 12 43 35](https://user-images.githubusercontent.com/19930241/95321040-bcc5d680-089a-11eb-9e40-59c9092594d1.png)
