### ISSUE TITLE
Accents not showing

### ISSUE THREAD

**Issue by Moose93** [vercel/hyper#3332] opened 2018-12-16 07:52 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **MacOS High Sierra 10.13.6**: 
- **Latest hyper release**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

I was working with my version of Hyper until today's morning when I started getting errors when I tried to write words with accents such as ´ñ ¨ .

![captura de pantalla 2018-12-16 a la s 01 21 16](https://user-images.githubusercontent.com/43086193/50051298-101ed180-00d5-11e9-9b3c-a30f06a7b63c.png)
![captura de pantalla 2018-12-16 a la s 01 21 27](https://user-images.githubusercontent.com/43086193/50051299-12812b80-00d5-11e9-86dc-a609d50b5116.png)

**Comment by nersoh** [comment] 2018-12-19 10:07
Could you give more details about the errors you're getting? I couldn't reproduce it on both versions
`2.0.0` and `2.1.0` of Hyper.

**Comment by Moose93** [comment] 2018-12-20 00:43
![captura de pantalla 2018-12-19 a la s 18 42 19](https://user-images.githubusercontent.com/43086193/50256845-ecea6f80-03bd-11e9-8cce-4523ce40a6a4.png)


Where the '??' are there should be an ñ

**Comment by Moose93** [comment] 2018-12-20 00:44
![captura de pantalla 2018-12-19 a la s 18 43 53](https://user-images.githubusercontent.com/43086193/50256864-0c819800-03be-11e9-8515-a77d42f93266.png)
Like here

**Comment by LabhanshAgrawal** [comment] 2020-06-30 16:22
Tested some accented characters & others with the [latest canary](https://github.com/vercel/hyper/actions/runs/151770461).
Using `touch ä ü ö Ä Ü Ö ß € § – — \' ¿ ¢ ¶ “ ¡ å ñ; ls`
Closing this as it seems to be working.
Feel free to open a new issue if you face any other problem

**Closed by LabhanshAgrawal** 2020-06-30 16:22 UTC
