### ISSUE TITLE
Text disappearing when using SF Mono as the font family

### ISSUE THREAD

**Issue by brunocloutier** [vercel/hyper#4360] opened 2020-03-09 13:59 UTC
- **OS version and name**: Mac OS Mojave (10.14.6)
- **Hyper.app version**: 3.1.0-canary.4
- **The issue is reproducible in vanilla Hyper.app**: No

I have been using SF Mono as my terminal font for years, and last week, whenever I started typing in Hyper, all the text would disappear. The terminal would load with the first line shown (computer name / user name), but after the first letter was typed, every thing would disappear.

After messing around in the config, disabling plugins and options, I have identified the issue being with the use of SF Mono. Reverting it back to Menlo fixed the issue. I have tested with other fonts, and the issue seams to be with SF Mono only. 

I am using the Canary version of Hyper (3.1.0), and the issue is not reproductible in vanilla (3.0.4) where SF Mono works fine.

**Comment by LabhanshAgrawal** [comment] 2020-03-09 16:53
Tried it out, but couldn't reproduce the issue. Maybe try to reinstall the font and Hyper.

**Comment by LabhanshAgrawal** [comment] 2020-03-20 11:15
@brunocloutier did you try to reinstall?

**Comment by JessicaSachs** [comment] 2020-03-28 00:48
Just reproduced this from a fresh install. It's happening 100% of the time for me -- same build -- using the following font family string: `fontFamily: '"MesloLGS NF", Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace'`

There's an exception being thrown where you're looking for /Network/Library/Fonts and that directory doesn't exist.

The fonts are loaded properly, then the exception is thrown and no fonts are rendered.

![Screen Shot 2020-03-27 at 8 44 36 PM](https://user-images.githubusercontent.com/2801156/77810633-d1afea80-706b-11ea-8fd6-910405e38ec3.png)

![Screen Shot 2020-03-27 at 8 44 06 PM](https://user-images.githubusercontent.com/2801156/77810630-d07ebd80-706b-11ea-9015-8454964c71dc.png)
![Screen Shot 2020-03-27 at 8 44 30 PM](https://user-images.githubusercontent.com/2801156/77810632-d1afea80-706b-11ea-9ef4-de1317a01a55.png)

You can't easily create `/Network/Fonts` because Catalina is doing crazy "read-only" filesystem stuff. ([link](https://stackoverflow.com/a/59421615))

**Comment by LabhanshAgrawal** [comment] 2020-03-28 06:35
@brunocloutier @JessicaSachs 
Can you try once with ligatures disabled, set `disableLigatures: true` in config.
The exception is thrown by the `font-ligatures` module which is used by `xterm-addon-ligatures`

**Comment by LabhanshAgrawal** [comment] 2020-04-14 17:05
@brunocloutier @JessicaSachs ping

**Comment by jbberinger** [comment] 2020-05-06 08:39
@LabhanshAgrawal Ran into the same issue with font disappearing after upgrading to canary. Disabling font ligatures fixed the problem for me.

**OS**: Ubuntu 19.10 x86_64
**Hyper.app version:** 3.1.0-canary.4
**Shell**: zsh 5.7.1
**fontFamily** 'MesloLGS NF, Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',

**Comment by LabhanshAgrawal** [comment] 2020-06-24 19:20
@JessicaSachs @jbberinger Can you reply with the link from where you downloaded the font, I want to try and reproduce the issue, so that we might not need to disable ligatures for it.

**Comment by jbberinger** [comment] 2020-06-24 21:58
@LabhanshAgrawal I'm using the popular zsh theme Powerlevel10k. It recommends the use of the Meslo Nerd font, which it installs during the setup wizard. I'm guessing that's where @JessicaSachs got the font as well.

https://github.com/romkatv/powerlevel10k#meslo-nerd-font-patched-for-powerlevel10k

**Comment by LabhanshAgrawal** [comment] 2020-07-05 13:40
we've disabled ligatures in the default config. I've created an issue to track this in xterm https://github.com/xtermjs/xterm.js/issues/2980
It should be fixed once that's closed.

**Closed by LabhanshAgrawal** 2020-07-05 13:40 UTC
Labels: 👆 Is Upstream
