### ISSUE TITLE
The accents are badly encoded.

### ISSUE THREAD

**Issue by julienr114** [vercel/hyper#1671] opened 2017-03-16 14:26 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra 10.12.2
- **Hyper.app version**:  1.3.1 (1.3.1.1628)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/julienr114/935c0556520d6afb72983f6571210e1e
- **Relevant information from devtools**: 
![capture d ecran 2017-03-16 a 14 13 31](https://cloud.githubusercontent.com/assets/10990867/24000793/8b52cada-0a5c-11e7-9c08-518674d40b13.png)

## Issue

The accents are badly encoded.
examples : é -> `<00c3><00a9>`
ô -> `<00c3><00b4>`
à -> `<00c3><00a0>`
ect.

![capture d ecran 2017-03-16 a 14 14 02](https://cloud.githubusercontent.com/assets/10990867/24000896/e67a3e70-0a5c-11e7-9d99-52f4a172f5d1.png)

**Comment by albinekb** [comment] 2017-03-16 17:21
They are correctly encoded for me, I remember @henrikdahl having the same problems with åäö, don't know whats causing this right off my head though 🤔

**Comment by mofux** [comment] 2017-03-16 19:11
I have seen the exact same problem when connecting to a remote host using ssh. In my case, the accents (ö, ä, ü) were okay locally, but once connected to the remote host they messed up (just like in the screenshot). I was able to reproduce the exact same behaviour with Terminal.app so I figured hyper was not to blame for that. Unfortunately this was a while ago and I can’t find a way to reproduce right now...

Maybe this is related:
https://superuser.com/questions/917523/mac-os-x-terminal-shows-special-characters-like-slash-space-etc-as-strange-cha


On 16 Mar 2017, at 18:21, Albin Ekblom <notifications@github.com<mailto:notifications@github.com>> wrote:


They are correctly encoded for me, I remember @henrikdahl<https://github.com/henrikdahl> having the same problems with åäö, don't know whats causing this right off my head though 🤔

**Comment by julienr114** [comment] 2017-03-17 07:58
Terminal.app encoded correctly.
![capture d ecran 2017-03-17 a 08 58 22](https://cloud.githubusercontent.com/assets/10990867/24034035/ea4cac20-0aef-11e7-857f-c3bccc8decc1.png)

**Comment by digitalfrood** [comment] 2017-03-22 07:54
Same for me on macOS 10.12.3. Problems with äöü which is necessary for german terminal users. Could it be something zsh / oh-my-zsh related? Or could hyper plugins do something bad to the encoding? 
```
  plugins: [
    'hyperline',
    'hyper-blink',
    'hyperterm-monokai',
    'hyperlinks',
    'hyper-tab-icons'
  ],
```
Working fine for me in other Terminal Applications, though. Hm.

**Comment by supercranky** [comment] 2017-03-23 08:05
Same for me with åäö

![skarmavbild 2017-03-23 kl 09 04 28](https://cloud.githubusercontent.com/assets/4178228/24237735/c9503228-0fa7-11e7-9ffc-051a1bca2688.png)

**Comment by hpohlmeyer** [comment] 2017-05-09 11:44
Same here:

<img width="295" alt="bildschirmfoto 2017-05-09 um 13 33 06" src="https://cloud.githubusercontent.com/assets/6564077/25848782/2670b5f2-34bc-11e7-8560-306e23bca00a.png">

Same here, wrongly encoded characters I have noticed:
ä, ü, ö, Ä, Ü, Ö, ß and other characters like €, §, –, —, ', ¿, ¢, ¶, “, ¡ and so on.

I am on a german QUERTZ layout, Trying an english QUERTY layout did not help either.

---
__my setup:__

I am using oh my zsh with pure prompt and the following plugins:

```
  plugins: [
    'hypercwd',
    'hyper-tab-icons',
    'hyperlinks',
    'hyperterm-1password'
  ],
```

**Comment by supercranky** [comment] 2017-09-15 10:54
Update: with version 1.4.4 the characters are displayed but when deleting text with backspace you can delete more characters than you should

![skarmavbild 2017-09-15 kl 12 52 44](https://user-images.githubusercontent.com/4178228/30479277-cd0b73bc-9a14-11e7-991b-947148e8dc72.png)

**Comment by julienr114** [comment] 2017-12-04 09:28
https://github.com/zeit/hyper/issues/1167#issuecomment-342453762

**Comment by julienr114** [comment] 2017-12-04 09:30
[This solution](https://github.com/zeit/hyper/issues/1167#issuecomment-342453762) solved this issue for me.

**Comment by LabhanshAgrawal** [comment] 2020-06-30 16:20
Tested all the mentioned characters with the [latest canary](https://github.com/vercel/hyper/actions/runs/151770461).
Using `echo "ä ü ö Ä Ü Ö ß € § – — ' ¿ ¢ ¶ “ ¡ å ñ"`
Closing this as it seems to be working.
Feel free to open a new issue if you face any other problem with the canary build

**Closed by LabhanshAgrawal** 2020-06-30 16:20 UTC
Labels: 🐛 Type: Bug
