### ISSUE TITLE
QR Code not being displayed in terminal (For react-native)

### ISSUE THREAD

**Issue by Zane-** [vercel/hyper#2746] opened 2018-03-08 15:01 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Build 16299
- **Hyper.app version**:  1.4.8 (when I tried on stable), 2.0.0-canary.14 (when I tried on canary)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: Is vanilla (on both canary and stable)

## Issue

QR Codes are not displayed in Hyper; not sure if this is a font issue or not, but it doesn't display with the default configuration, nor with a powerline font selected.

This problem is present with the default .hyper.js configuration.

Below is WSL on the left and hyper on the right
![](https://user-images.githubusercontent.com/6345012/37157320-80d46f6e-22b6-11e8-8995-eb1caec5a6e1.jpg)

**Comment by chabou** [comment] 2018-03-08 15:08
Can you precise your hyper version?
"Latest" today will not be "Latest" in fex days :)

**Comment by Zane-** [comment] 2018-03-20 17:36
@bgw 
qrcode-terminal does not seem to work in hyper for me. This is running on vanilla 2.0.0-canary.14 just like you. Running WSL Ubuntu as my shell, which doesn't seem to be the issue since it displays fine in the Windows cmd.
<img width="371" alt="10be2f9ef81f4858f12540cc31500f39" src="https://user-images.githubusercontent.com/6345012/37672105-9fd42fe4-2c43-11e8-91ba-43ade6e7aa21.png">

**Comment by phifa** [comment] 2018-04-18 12:31
same for me, git bash show the qr code, but not with hyper and wsl

**Comment by vikas5914** [comment] 2018-04-23 07:59
I am using Hyper 2.0.0 (stable) with cmd and Windows 10 17643. )

It's not showing the QR code.  it was showing older version.

**Comment by Stanzilla** [comment] 2018-04-23 17:52
Hey there, to verify if this is indeed a Hyper issue or upstream at https://github.com/xtermjs/xterm.js/ could you please test if another xterm.js powered terminal shows the same problem you are experiencing? I suggest using https://github.com/Microsoft/vscode for testing. Thanks!

**Comment by vikas5914** [comment] 2018-04-23 19:46
@StanzillaI just tried vs code. it's not showing the QR code.  So I think the problem is in Xterm.js

**Comment by Stanzilla** [comment] 2018-04-23 19:51
Thanks for verifying! See you over at https://github.com/xtermjs/xterm.js/issues :)

**Comment by rojagit** [comment] 2018-07-25 17:03
Just by the number of issues (tickets) opened and closed without resolve for this bug (see pic) it is obvious that MS VS Code team has no interest in resolving it. 

So much for vying to be a fore-runner in the IDE marketplace. First thing I'm gonna do is uninstall VS Code on all my machines as their support is typical MS. 

@vikas5914 note that there are many issues for this bug, not just one, most locked down so no more whining to a team that is incapable of fixing its bugs.

And to think I got excited recently when I saw VSCode had a customizable integrated console. I tried 3, none worked.

And most surprisingly, the Update failed, so it uninstalled itself. Nice !

![image](https://user-images.githubusercontent.com/4193031/43215374-f8ea7604-9009-11e8-8ec7-41fed7ddb9d3.png)

**Comment by rojagit** [comment] 2018-07-25 17:05
Just by the number of issues (tickets) opened and closed without resolve for this bug (see pic) it is obvious that MS VS Code team has no interest in resolving it.

So much for vying to be a fore-runner in the IDE marketplace. First thing I'm gonna do is uninstall VS Code on all my machines as their support is typical MS.

@vikas5914 note that there are many issues for this bug, not just one, most locked down so no more whining to a team that is incapable of fixing its bugs.

And to think I got excited recently when I saw VSCode had a customizable integrated console. I tried 3, none worked.

And most surprisingly, the Update failed, so it uninstalled itself. Nice !

![image](https://user-images.githubusercontent.com/4193031/43215877-5ce019f6-900b-11e8-8268-021a44f14846.png)

**Comment by vikas5914** [comment] 2018-08-02 13:53
@rojagit The problem is there is no issue created on the upstream software: 

1. https://github.com/xtermjs/xterm.js/issues?utf8=%E2%9C%93&q=QR
2. https://github.com/rprichard/winpty/issues?utf8=%E2%9C%93&q=QR

**Comment by MrARC** [comment] 2018-12-17 05:57
Hi, i was experiencing myself the same behaviour, today hyper was updated to 2.1.0 and this problem no longer exists (at least for me, can someone else try?)

**Comment by LabhanshAgrawal** [comment] 2020-07-06 06:47
Tested with latest [build](https://github.com/vercel/hyper/actions/runs/157826845)
seems to be working properly
Feel free to open a new issue if you face any problems

**Closed by LabhanshAgrawal** 2020-07-06 06:47 UTC
Labels: 👆 Is Upstream, 🖼 Platform: Windows
