### ISSUE TITLE
Request: Ability to drag file to hyper and show path similar to other terminal applications.

### ISSUE THREAD

**Issue by chadmandoo** [vercel/hyper#3742] opened 2019-06-19 14:53 UTC
Would be nice to be able to drag a file into Hyper and display its path.

**Comment by VdustR** [comment] 2019-06-22 16:17
Same request

It doesn't work since v3.0.0+ and works fine until v2.1.2.

**Comment by ethanentW** [comment] 2019-07-03 17:32
I'd appreciate the ability to do this as well.

**Comment by doomlaser** [comment] 2019-07-14 15:53
This would be a critical feature for me

**Comment by mihaiserban** [comment] 2019-11-21 09:29
frustrating that this used to work before, but it was removed from v3+

**Comment by bet4it** [comment] 2019-11-21 11:13
Duplicate of #3582

It has been fixed in #3690
Wait for the next release

**Closed** 2020-06-26 15:53 UTC
