### ISSUE TITLE
Opening Preferences does not work

### ISSUE THREAD

**Issue by glensc** [vercel/hyper#5467] opened 2021-03-31 09:42 UTC
- [x] Your Hyper.app version is **3.0.2**. Please verify your using the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
  - [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

  ---
  - **Any relevant information from devtools?** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:

  - **Is the issue reproducible in vanilla Hyper.app?**

## Issue

1. <del>Noticed font size, started hitting `cmd`+`=` (US keyboard) to increase the font size and a notification `[Notification] Plugin error: Plugins decorating Term has been disabled because of a plugin crash. Check Developer Tools for details.`</del>: EDIT: Solved, not reproducible with Canary build.
2. Opening Preferences (`cmd`+`,`) results in a crash or something (dialog does not appear and terminal is `this.blur()`-ed) and a notification dialog appears about config being reloaded.

![image](https://user-images.githubusercontent.com/199095/113124700-771d1180-921e-11eb-9247-25517c9c6b1f.png)

 - **Hyper version**: undefined "3.0.2"

 - **OS ARCH VERSION:** darwin x64 20.3.0 (Installed via brew cask)
 - **Electron:** 3.1.3  **LANG:** undefined
 - **SHELL:** /bin/bash   **TERM:** undefined

  <details>
    <summary><strong> ~/.hyper.js contents</strong></summary>
      <pre>
        <code>
          {
  "updateChannel": "stable",
  "fontSize": 12,
  "fontFamily": "Menlo, \"DejaVu Sans Mono\", Consolas, \"Lucida Console\", monospace",
  "fontWeight": "normal",
  "fontWeightBold": "bold",
  "lineHeight": 1,
  "letterSpacing": 0,
  "cursorColor": "rgba(248,28,229,0.8)",
  "cursorAccentColor": "#000",
  "cursorShape": "BLOCK",
  "cursorBlink": false,
  "foregroundColor": "#fff",
  "backgroundColor": "#000",
  "selectionColor": "rgba(248,28,229,0.3)",
  "borderColor": "#333",
  "css": "",
  "termCSS": "",
  "showHamburgerMenu": "",
  "showWindowControls": "",
  "padding": "12px 14px",
  "colors": {
    "black": "#000000",
    "red": "#C51E14",
    "green": "#1DC121",
    "yellow": "#C7C329",
    "blue": "#0A2FC4",
    "magenta": "#C839C5",
    "cyan": "#20C5C6",
    "white": "#C7C7C7",
    "lightBlack": "#686868",
    "lightRed": "#FD6F6B",
    "lightGreen": "#67F86F",
    "lightYellow": "#FFFA72",
    "lightBlue": "#6A76FB",
    "lightMagenta": "#FD7CFC",
    "lightCyan": "#68FDFE",
    "lightWhite": "#FFFFFF"
  },
  "shell": "",
  "shellArgs": [
    "--login"
  ],
  "env": {},
  "bell": "SOUND",
  "copyOnSelect": false,
  "defaultSSHApp": true,
  "quickEdit": false,
  "macOptionSelectionMode": "vertical",
  "webGLRenderer": true
}

          {
  "plugins": [],
  "localPlugins": []
}
        </code>
      </pre>
  </details>

**Comment by LabhanshAgrawal** [comment] 2021-03-31 12:47
Try with the latest build from https://github.com/vercel/hyper/actions/runs/700190262#artifacts

**Comment by glensc** [comment] 2021-03-31 14:03
@LabhanshAgrawal font zoom in is better (no crashes), but opening prefs still crashes.

**Comment by LabhanshAgrawal** [comment] 2021-03-31 15:21
That's not a crash.
It just watches for file events on the config file, and does a refresh based on the content. Doesn't impact anything if you haven't made any changes.

**Comment by LabhanshAgrawal** [comment] 2021-03-31 17:00
Oh
what's the default app for js files on your system?
you can try `open ~/.hyper.js` and check

**Comment by LabhanshAgrawal** [comment] 2021-03-31 17:24
Closing this as the issue is solved
Contributions are welcome for features and improvements

Thanks

**Closed by LabhanshAgrawal** 2021-03-31 17:24 UTC
