### ISSUE TITLE
Magnet not able to resize Hyper

### ISSUE THREAD

**Issue by jlengrand** [vercel/hyper#3768] opened 2019-07-24 17:30 UTC
Hi there, 

- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Mojave 10.14.5 (18F132)
- **Hyper.app version**: 3.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 

The default with the following plugins :

```
  plugins: [
    "hyper-statusline",
    "hyperterm-material-theme",
    "hyper-tabs-enhanced"
  ],
```

- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 

N/A I think. Happy to add

- **The issue is reproducible in vanilla Hyper.app**: 

Plugins are only cosmetic.

## Issue

I am using [Magnet](https://magnet.crowdcafe.com/) as window manager on my Mac. Magnet allows you to manage your windows using keyboard shortcuts, and it works on all of the software that I use. 

However, magnet is not able to resize and reorder Hyper for some reason. Is that a known issue? I would guess that it can be related to the fact that Magnet does not seem to be using the same windows as most software (there's no close / expand / .... / button). 

I'm happy to dive further into it if someone gives me some more pointers as to what to look into :)

**Comment by jlengrand** [comment] 2019-07-24 21:27
I was looking further into how to solve this issue, and it does not seem like custom mapping could do the trick. 

The list mentioned [here](https://github.com/zeit/hyper/blob/master/app/keymaps/darwin.json) does not seem to contain 'take left half of the screen', right half, top half, ....

**Comment by lndwn** [comment] 2019-10-28 23:00
@jlengrand I was seeing the same issue. I uninstalled `hyper-tabs-enhanced` and Magnet started working again after re-launching.

**Comment by jpmarra** [comment] 2020-07-07 15:32
> @jlengrand I was seeing the same issue. I uninstalled `hyper-tabs-enhanced` and Magnet started working again after re-launching.

This did the trick for me. Thanks @lndwn!

**Comment by LabhanshAgrawal** [comment] 2020-07-07 15:42
closing as it seems to be caused by a plugin, not hyper

**Closed by LabhanshAgrawal** 2020-07-07 15:42 UTC
Labels: 👇Is Plugin
