### ISSUE TITLE
Window gets stuck after closing a tab

### ISSUE THREAD

**Issue by Roshan931** [vercel/hyper#4837] opened 2020-08-27 10:38 UTC
Steps:

- Make window full screen
- Open a new tab with `cmd+d` while being in fullscreen
- Make the window smaller by double tapping on the title bar
- Close the new tab with `cmd+w`

The main tab gets stuck and sometimes makes the content inside weirdly scaled.

**Comment by LabhanshAgrawal** [comment] 2021-10-04 05:31
Duplicate of #3951

**Closed by LabhanshAgrawal** 2021-10-04 05:31 UTC
