### ISSUE TITLE
Multiple new lines on Hyper startup

### ISSUE THREAD

**Issue by brianhafferkamp** [vercel/hyper#4504] opened 2020-04-20 22:47 UTC
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Cataline 10.15.3
- **Hyper.app version**: 3.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/brianhafferkamp/6bd1ccfc88d312c34617860f0bc7dd3c
- **The issue is reproducible in vanilla Hyper.app**: Yes, tested without plugins and saw the same problem

## Issue
I'm using powerlevel10k with oh-my-zsh (zsh v5.7.1) in the Hyper terminal (3.0.2). I'm noticing an issue where, when I initialize my Hyper terminal, I'm seeing multiple new lines created as seen below:
<img width="875" alt="Screen Shot 2020-04-20 at 4 22 20 PM" src="https://user-images.githubusercontent.com/29557595/79805455-659b6c00-8323-11ea-9d6c-825f3b11e172.png">

Previously, I was seeing a `%` at the top, which is a fairly well known issue. I resolved this by adding `unsetopt PROMPT_SP` to my `.zshrc`. However, this did not fix the multiple new lines.

I am not seeing this issue in the Mac Terminal. It is possible that this could be an issue with powerlevel10k, as I do not see this issue if I use a different oh-my-zsh theme. I have opened a [similar ticket](https://github.com/romkatv/powerlevel10k/issues/645) in the powerlevel10k repo

Any ideas on how I might be able to fix this?

Thanks!

**Comment by LabhanshAgrawal** [comment] 2020-06-30 07:03
Looks like residual artifacts from resizing.
Does this also happen if you open a new tab?
Try out the latest [ci build](https://github.com/vercel/hyper/actions/runs/151770461) once to see if the issue is still there.

**Comment by mr-bjerre** [comment] 2020-09-11 09:41
Same for me...

**Comment by LabhanshAgrawal** [comment] 2021-02-05 13:01
seems to be fixed in romkatv/powerlevel10k@ae32fd58b3623b52005c72fb1edcb09ab753ad45

**Closed by LabhanshAgrawal** 2021-02-05 13:01 UTC

**Comment by LabhanshAgrawal** [comment] 2021-02-05 13:03
also tested working on latest build (tested on mac)

**Comment by Jrb1x** [comment] 2021-02-15 20:40
@LabhanshAgrawal How did you get this to work? Still getting the lines.

**Comment by LabhanshAgrawal** [comment] 2021-02-16 04:31
@Jrb1x update powerlevel10k to latest commit
I test on the latest build from [ci](https://github.com/vercel/hyper/actions/runs/568537952#artifacts)
