### ISSUE TITLE
hyper CLI still shows old version and likely causing other issues

### ISSUE THREAD

**Issue by pcnate** [vercel/hyper#3602] opened 2019-05-06 14:01 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: `Windows 10 1803 Build 17134.706`
- **Hyper.app version**: `3.0.0`
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 'https://gist.github.com/pcnate/fcc7b45394d0c8d74f4b4f98ce329fa5'
- **Relevant information from devtools** : null
- **The issue is reproducible in vanilla Hyper.app**: true

## Issue
When executing `hyper version` it shows `2.1.2` after upgrading to `3.0.0`.

After a reboot, the issue remains. I could manually fix my path but I would rather wait and have it properly fixed in an update. I'll deal with it until then.

This could be the root of the issues with the wrong config being used and not being able to install plugins.

**Comment by ZaLiTHkA** [comment] 2019-05-06 14:32
with regards to your link from #3500: the output of `hyper version` on my side definitely shows `3.0.0`, so this is definitely a separate issue.

that said, I *did* have a few environment issues to sort out after upgrading from `2.1.2`: the upgrade process didn't remove the `%LOCALAPPDATA%\hyper\app-2.1.2\` folder and the paths in my current environment's `%PATH%` variable were still pointing to the old version.

I ended up removing `2.1.2`, deleting all relevant files and plugin cache folders (look in both `%LOCALAPPDATA%` and `%APPDATA%`), then log out and log in again before installing `3.0.0`.

another way I could tell that my environment variables were screwy is running `hyper` from a new terminal window.

if you don't mind, try something for me quickly:

* open Hyper
* check the output of `hyper version`
* run `hyper` to launch another instance
* check the output of `hyper version` again

if the version shown in the second instance shows `3.0.0`, then you most likely also have environment variable issues.. in this case, I would suggest you try remove all Hyper related files and do a fresh install.

---

one other issue I had, which it seems you don't, is that my `%PATH%` variable *type* somehow changed back to the "static" type that doesn't expand variables. this only happened after installing `3.0.0`, but I haven't managed to reproduce it so I can't be sure..

**Comment by pcnate** [comment] 2019-05-06 14:41
both output `2.1.2`.

Maybe it will changed when I log back into OS but I don't plan on doing that today.

**Comment by ZaLiTHkA** [comment] 2019-05-06 14:44
interesting.. I'm finishing work in a little while, so I'll pay more attention to the process when I upgrade Hyper on my personal laptop this evening to see if I can work out anything more helpful for you. :)

**Comment by pshah123** [comment] 2019-05-06 14:49
My hyper CLI shows 3.0.0, but running hyper using the CLI now opens Hyper but with loading in my previous settings & plugins perfectly while running Hyper via the executable in Windows does not.

**Comment by ZaLiTHkA** [comment] 2019-05-07 16:25
> ...when I upgrade Hyper on my personal laptop this evening to see if I can work out anything more helpful for you. :)

had a bit of a family emergency last night, so I only got to dig into this now.. sorry about that.

---

from what I've worked out now; the Hyper 3 Windows setup does update the `PATH` variable, but it also changes the `type` from `REG_EXPAND_SZ` to the simpler `REG_SZ`. so basically if you have any `%VARIABLE%` entries in your path, it breaks completely. this can be fixed by either changing the type through `regedit.exe` directly, or by opening the Windows environment variables settings window, editing the `PATH` variable and simply saving it without making changes.

obviously keep in mind you'll need to close and reopen any running instances of Hyper to get this new environment, just because, well, Microsoft. O.o the safest option is to just log out and log in again.

but basically, after that, the `hyper version` command now shows `3.0.0` regardless of how I choose launch it.

**Comment by NileshSP** [comment] 2019-08-23 05:44
Was facing the relevant issue and after troubleshooting figured out that the issue occurs due to settings filepath are accessed & updated differently during certain operations and is for windows specific cases only as far i could understand from code

During actual runtime, settings file is loaded & modified in filepath as 
 

>  C:\Users\\{userloggedin}\AppData\Roaming\\**Electron**\\.hyper.js


whereas it should be 

 

>  C:\Users\\{userloggedin}\AppData\Roaming\\**Hyper**\\.hyper.js


and is probably because of `app.getPath('userData')`  which returns `...\Electron\.hyper.js`  instead of  `...\Hyper\.hyper.js` location  https://github.com/zeit/hyper/blob/758e93c21e98556dd50acd81e8dc27615eebe787/app/config/paths.js#L17



while in hyper-cli `path.join(process.env.APPDATA, 'Hyper')` always returns 

>  C:\Users\\{userloggedin}\AppData\Roaming\\**Hyper**\\.hyper.js

https://github.com/zeit/hyper/blob/758e93c21e98556dd50acd81e8dc27615eebe787/cli/api.js#L14

Kindly confirm the analysis and if possible can help with a PR for a solution

**Comment by LabhanshAgrawal** [comment] 2021-02-19 12:49
The issues mentioned here seem to be fixed in canary branch
please try a build from https://github.com/vercel/hyper/actions/runs/568537952#artifacts
closing this, please open a new issue if you face any problems with the ci build

**Closed by LabhanshAgrawal** 2021-02-19 12:49 UTC
Labels: ⌨️ CLI tool, 🐛 Type: Bug
