### ISSUE TITLE
Switching tabs using keyboard shortcuts only works once

### ISSUE THREAD

**Issue by hugofloss** [vercel/hyper#1205] opened 2016-12-14 14:13 UTC
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

## Software
- MacOS Sierra 10.12.1 (16B2555)
- Hyper.is Version 1.0.0 (1.0.0.1303)

## Reproduce issue
1. Create a new tab with `cmd+t`
2. Switch tabs with `cmd+shift+[` or `cmd+shift+]`
3. It successfully switches tab. Switch back again to the previous tab with `cmd+shift+[` or `cmd+shift+]`
4. It fails to switch tabs. Only after explicitly clicking my mouse cursor in the window I can successfully switch back and forth tabs as much as I'd like.

**Comment by bj7** [comment] 2017-01-20 13:32
I can confirm this behavior as well on macOS Sierra 10.12.2 with hyper 1.1.0 (1.1.0.1408). I will add,

- It only occurs on first opening a new tab and switching. It switches once then stops.
- It occurs if using `cmd-#[1-9]` to switch to numbered window (using the same flow as above).
- Not a serious bug, just an annoyance. 

If no one objects, I would like to take a crack at it this weekend possibly. I have duties at a wedding, but I might be able to spend some time on Sunday to shed some more light on what the cause is.

**Comment by ppot** [comment] 2017-02-09 03:13
Fixed in my rework.

**Comment by LabhanshAgrawal** [comment] 2021-02-04 08:18
Fixed in canary

**Closed by LabhanshAgrawal** 2021-02-04 08:18 UTC
Labels: 🐛 Type: Bug
