### ISSUE TITLE
Any dotnet commands break instantly

### ISSUE THREAD

**Issue by fjlaubscher** [vercel/hyper#3384] opened 2019-01-04 10:12 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Mojave 10.14.2
- **Hyper.app version**: 2.1.0 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [Gist](https://gist.github.com/fjlaubscher/bb465503a5946a2105267a0bfe170430)
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`

## Issue

Running any `dotnet` commands in Hyper seem to break instantly.
I've tried running this in the mac terminal and iTerm2 and it works fine.
![hyper-crash](https://user-images.githubusercontent.com/5119031/50683208-f3adef00-1019-11e9-9fd9-b638d570bc0a.gif)

**Comment by ArCiGo** [comment] 2020-07-29 14:29
Is there any workaround for this?

**Comment by LabhanshAgrawal** [comment] 2021-03-25 07:51
Can't reproduce on latest build
Closing as this was for v2, try a build from [ci](https://github.com/vercel/hyper/actions/runs/675890687#artifacts) and reopen this if it happens with the new build also.

**Closed by LabhanshAgrawal** 2021-03-25 07:51 UTC
