### ISSUE TITLE
Funky resizing issues

### ISSUE THREAD

**Issue by Stanzilla** [vercel/hyper#2421] opened 2017-11-03 21:45 UTC
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 1709
- **Hyper.app version**: 2.1.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**:  https://gist.github.com/Stanzilla/e8ef5c460bbeb8b61699db1518ee7a5a
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

Various display bugs happening when resizing the terminal with multiple tabs open, happening on 2.1.0

https://dl.dropboxusercontent.com/s/gmlpceuwd2i1byw/2017-11-03_22-34-18.webm

It works fine in 1.4.8 so it is a regression.

**Comment by jaller94** [comment] 2017-11-10 21:09
This is not limited to Windows. I am also affected on MacOS 10.13.

**Comment by NicholasJohn16** [comment] 2017-11-15 12:03
I just reinstalled Hyper 1.4.8 and I'm having this same issue. Even happens when you have panes and you resize the window.

![hyper1 4 8](https://user-images.githubusercontent.com/1107114/32835109-e4e4ba28-c9d2-11e7-9a76-d2626f260e27.png)

**Comment by Stanzilla** [comment] 2017-11-15 12:29
I just tried on 1.4.8 yesterday and could not repro, weird.

**Comment by jaller94** [comment] 2017-11-15 16:02
In 2.1.0 it doesn't affect my first tab of a window.

1. Open Hyper.
2. `history` (a program with output)
3. Open another tab.
4. `history`
5. Resize the window.
6. Switch to the first tab. All looks good.
7. Resize the window.
8. Switch to the second tab. The output of the history command can be seen, however, with only one character per line.

**Comment by NomNuggetNom** [comment] 2017-11-22 18:21
Also suffering from this issue and I can reproduce every time. I'm on 2.1.1.

**Comment by NomNuggetNom** [comment] 2017-12-09 03:58
Bump on this. Makes the terminal unusable. Any more info needed?

**Comment by jaller94** [comment] 2017-12-09 19:19
I wouldn't say unusable. Since the pre-releases are out I'm only using
those because of the performance gain. However, I am affeced of the resize
bug roughtly every 10 minutes.

To me it seems like the size indicator at the bottom right iterates quicky
through all tabs. When changing the size by one unit, I multiple values
show up sequentially. Some of them being the actual size like "64x32" and
others being "1x1". That's when I know some tab(s) have been squeezed.

**Comment by dfenster** [comment] 2017-12-11 19:16
I also have this problem

**Comment by LabhanshAgrawal** [comment] 2020-07-08 11:17
@Stanzilla I guess we should close this issue as it was for v2 and I don't think it's present in canary now.

**Closed** 2020-07-08 11:43 UTC
Labels: 🐛 Type: Bug, 💛 Priority: Medium
